### ISSUE TITLE
Random yaw rotation of sampled data

### ISSUE THREAD

**Issue by kazuto1011** [hancyran/LiDAR-Diffusion#10]
Thank you for sharing the excellent work! Following the README, I've just tried the unconditional generation with:
```bash
python scripts/sample.py -d kitti -r models/lidm/kitti/uncond_wo_logscale/model.ckpt -n 10
```
and the produced results were like:

![point_clouds](https://github.com/hancyran/LiDAR-Diffusion/assets/9032347/9cd3fa0f-b201-4286-a643-b5af8a350005)
![range_images](https://github.com/hancyran/LiDAR-Diffusion/assets/9032347/c55ac0cc-bec3-4dc6-939e-405cdeeb8584)

It looks like that the point clouds and the corresponding range images are randomly rotated in a yaw direction (the released 2k samples are also). Is it expected behavior for evaluation?

In contrast, the point clouds of LiDARGen are aligned like GT point clouds (e.g. the ego-vehicle shadows):

![point_clouds_2](https://github.com/hancyran/LiDAR-Diffusion/assets/9032347/f4e44e4b-6969-4ca6-a1b2-639e3de938d9)

Besides these, I found some missing information in running the above demo.
- `pip` is required for the conda environment.
- `scipy` & `joblib` are missing in installing dependencies
- `models/first_stage_models/kitti/f_c2_p4_wo_logscale` should be renamed to `models/first_stage_models/kitti/f_c2_p4_wo_ls` according to the released weights.

**Comment by hancyran** [comment]
Thanks for your feedback! 

Exactly. The randomly rotation is predictable, as we train diffusion models with random rotation augmentation. This helps the models learn more robustly, but also leads to producing randomly rotated samples for **unconditional** task. During our evaluation for unconditional generation task, we expect the random rotation a less prioritized case. If it is non-negligibly critical for your case, simply disable rotation augmentation in the config file to train LiDM from scratch (no need to retrain the autoencoder, commonly won't take too much time) and it will generate non-rotated samples as expected. 

Thank you for pointing out the missing info, and we will update it accordingly in our repo.

**Comment by kazuto1011** [comment]
Thank you for your quick response. According to the LiDM config, the rotation augmentation is already disabled by default.
https://github.com/hancyran/LiDAR-Diffusion/blob/8416ddbbda881553088109a66badf71ff11999e0/models/lidm/kitti/uncond_wo_logscale/config.yaml#L72
After investigating a bit more, I think this may be due to circular padding, which makes the convolutional models invariant to the rotation. Simply concatenating spatial information to the DM input like LiDARGen or removing the circular padding would solve the issue. I've also been working on LiDAR generative models and followed a similar biasing approach in [my current work](https://github.com/kazuto1011/r2dm). I think the global pooling in the current evaluation mitigates the rotational variation issue. I will try it out.

**Comment by hancyran** [comment]
Thanks for your careful feedback! This can be an interesting finding around the rotation issue. I will include this point in our next training. I will fix it later and if you don't mind, I will list you as an unofficial contributor in our README page (or if you would love to, feel free to submit a request).

**Comment by kazuto1011** [comment]
I would appreciate if you could try it due to my limited computational resources. I don't mind for listing. Thank you very much.

**Comment by ren-shi-qi** [comment]
Hi @hancyran, thank you for your excellent work!

I’m wondering if there has been any solution or further progress regarding the rotation issue mentioned earlier?

Appreciate your time!
