### ISSUE TITLE
retrain LiDAR-Diffusion model

### ISSUE THREAD

**Issue by HaiyunW** [hancyran/LiDAR-Diffusion#4]
@hancyran Hello, how can I retrain LiDAR-Diffusion Model.? I want to use it as a backbone for my research. Thank you very much!

**Comment by hancyran** [comment]
Thank you for your feedback! We have updated our codebase with a main.py file for training and some text in README about  how to train your own LiDAR Diffusion. Feel free for any further questions!

**Comment by HaiyunW** [comment]
@hancyran Thank you for your quick reply! Could you show me the root path of the main.py file? I have some difficulty finding the  it.

**Comment by hancyran** [comment]
@HaiyunW Just forgot to commit it. You can check it right now.
