### ISSUE TITLE
Train Diffusion Model

### ISSUE THREAD

**Issue by waldiwunder** [hancyran/LiDAR-Diffusion#7]
Hello! Thanks for your interesting paper!

I want to learn to train the model from scratch. I trained first the autoencoder on the KITTI dataset and it worked fine (I compared samples with the pretrained autoencoder and the self-trained autoencoder using the pretrained diffusion model; I could successfully load the self-trained autoencoder).

However, when I want to train the diffusion model now with 
python main.py -b configs/lidar_diffusion/kitti/uncond_c2_p4.yaml -t --gpus 0,

```
If encountered a problem (both for the self-trained autoencoder and the pretrained one):
RuntimeError: Error(s) in loading state_dict for VQModelInterface:
	size mismatch for decoder.conv_out.weight: copying a param with shape torch.Size([1, 64, 1, 4]) from checkpoint, the shape in current model is torch.Size([2, 64, 1, 4]).
	size mismatch for decoder.conv_out.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([2]).
```

I realized that in the config file for training is stated:
`out_ch: 2`
In the config file for unconditional sampling however:
`out_ch: 1`

I changed the config file for training to `out_ch: 1`, and the training started. Now I have another problem, the code is stuck here.

```
Validation sanity check:   0%|                                                                                                       | 0/2 [00:00<?, ?it/s]
> /home/XXX/LiDM-main/lidm/models/diffusion/ddpm.py(659)get_input()
-> x = super().get_input(batch, k)
```

I commented now line 658 in ddpm.py 
`# import pdb; pdb.set_trace()`

Is this correct that these lines need to be changed or did I do something woring? The training now is running, but it has not completed so far, so I do not know if the result is good. I give an update when it finished.
Thanks for your work again!

**Comment by hancyran** [comment]
Thanks for your feedback! I think everything you have done is right, just suggest that train your diffusion model after checking the autoencoder settings inside its config (`uncond_c2_p4.yaml`) file is exactly the same as the settings of the autoencoder you have trained before, and make sure the checkpoint path (`ckpt_path`) inside file `uncond_c2_p4.yaml` points to your trained autoencoder.

**Comment by waldiwunder** [comment]
Thank you very much! This helped me a lot. The images after the first epoch look good, I continue training.
