### ISSUE TITLE
LiDAR Compression Config Files

### ISSUE THREAD

**Issue by HaiyunW** [hancyran/LiDAR-Diffusion#8]
Could you please update other config files for lidar conmpression? Such as curvewise factor=1，patchwise factor=8 and so on.

**Comment by hancyran** [comment]
You can find them in the folder `models/first_stage_models/ablate` for all the configs of lidar compression. Just remove the parameter `max_steps` and `sync_batchnorm` will be the config file that you expect.  Besides. you could also find both lidar compression and lidar diffusion config files of all settings  in the provided Google Drive directories from `DESIGN.md`.
